def inputs(a):
    print(a)
    print(a.ndim)
    print(a.shape)
    print(a.size)
    print(a.itemsize)
    print(a.dtype)
import numpy as np
np.random.seed(144)
n = int(input("Nhap vao n: "))
a = np.array(np.random.randint(1, 15, n))
b = np.array([int(i) for i in range(0, 200, 2)])
c = np.zeros((n, n))
d = np.eye(n)
e = np.diag(a)
inputs(a)
inputs(b)
inputs(c)
inputs(d)
inputs(e)
